### PR TITLE
Update for PureScript 0.15, add CI action

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by nwolverson** [comment]
Thanks, I rather forgot about this repo for some time.

I don't see a way to get that CI action to run on this PR that adds it so I'll go ahead and merge.

**Comment by garyb** [comment]
Thanks! The action should be okay, I had it run on my branch before opening this 🙂

**Comment by nwolverson** [comment]
It's green, tagged a new version.

Are you using this in an active project? Happy to add a maintainer if you want. Though there is about a commiter per PS major release :)

**Comment by garyb** [comment]
Yeah I do use it in a project - being added as a maintainer sounds good to me! You're always responsive anyway, but at least you wouldn't have to think about it then when it next needs an update :smile:

**Pull request merged**
